---
title: "Our Report"
author: "Tech Lab"
date: "2024-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("data_prep.R")

```

## Section 1

Introduction to Section 1 and its key concepts. 

### Figure 1: Individuals by Gender

```{r fig 1, echo=FALSE, warning=FALSE, fig.alt="this is where we add alt text", out.width="100%"}


fig_1 <- plot_ly(df_indivs_gender,
                 x = ~gender,
                 y = ~individuals,
                 type = "bar"
                # orientation = "h",
               #  name = "Gender",
               #  marker = list(color = "#00205b"),
               #  text = ~individuals,
                # textposition = "outside"
                # hovertemplate = ~paste0(gender, " : ", individuals)
                ) 
#%>% 
 # layout(yaxis = list(title = ""),
 #        xaxis = list(title = "Gender",
   #                   categoryorder = "total descending"))

fig_1 <- config(fig_1, displayModeBar = FALSE)

fig_1

```

This is where we will add some commentary to explain the message conveyed by the chart.


```{r}
fig2 <- plot_ly(df_gender_ageband_allyrs,
                x = ~year,
                y = ~male_under_16,
                name = "Male under 16",
                type = "scatter",
                mode = "lines",
                line = list(color = "#b88700")) %>%
 
  layout(xaxis = list(gridcolor = "#fff",
                      showticklabels = TRUE,
                      title = "",
                      type = "date",
                      tickvals = ~unique(year),
                      tickformat = "%Y"),
         yaxis = list(range = c(0, 10)))

fig2 <- config(fig2, displayModeBar = FALSE)

fig2
  
```

